# Generated by Django 2.2.17 on 2021-01-26 01:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('booking_time', models.DateTimeField(default=datetime.datetime(2021, 1, 26, 1, 38, 31, 545706))),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
            ],
        ),
    ]
