# Generated by Django 2.2.17 on 2021-01-26 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 1, 38, 47, 142049)),
        ),
    ]
